import type { User } from "@/types/user";
import type {
  Property,
  PropertyApplication,
  PropertyReview,
  TenantReview,
} from "@/types/property";
import type { Lease } from "@/types/lease";
import type { Payment } from "@/types/payment";
import type { MaintenanceRequest } from "@/types/maintenance";
import type { Notification, ActivityItem, DealStage } from "@/types/common";

// ── Users ──────────────────────────────────────────────
export const mockUsers: User[] = [
  {
    id: "u1",
    firstName: "Chinedu",
    lastName: "Okafor",
    email: "chinedu@gmail.com",
    phone: "08012345678",
    role: "customer",
    kycStatus: "verified",
    state: "Lagos",
    city: "Lekki",
    createdAt: "2025-09-15",
    isActive: true,
  },
  {
    id: "u2",
    firstName: "Aisha",
    lastName: "Abdullahi",
    email: "aisha@gmail.com",
    phone: "08098765432",
    role: "landlord",
    kycStatus: "verified",
    state: "FCT Abuja",
    city: "Maitama",
    createdAt: "2025-06-10",
    isActive: true,
  },
  {
    id: "u3",
    firstName: "Emeka",
    lastName: "Nwosu",
    email: "emeka@gmail.com",
    phone: "07034567890",
    role: "agent",
    kycStatus: "verified",
    state: "Lagos",
    city: "Victoria Island",
    createdAt: "2025-07-20",
    isActive: true,
  },
  {
    id: "u4",
    firstName: "Fatima",
    lastName: "Bello",
    email: "fatima@smoothrent.io",
    phone: "08145678901",
    role: "admin",
    kycStatus: "verified",
    state: "FCT Abuja",
    city: "Wuse",
    createdAt: "2025-01-01",
    isActive: true,
  },
  {
    id: "u5",
    firstName: "Oluwaseun",
    lastName: "Adeyemi",
    email: "seun@gmail.com",
    phone: "09087654321",
    role: "customer",
    kycStatus: "pending",
    state: "Lagos",
    city: "Yaba",
    createdAt: "2026-01-05",
    isActive: true,
  },
  {
    id: "u6",
    firstName: "Amaka",
    lastName: "Eze",
    email: "amaka@gmail.com",
    phone: "08167890123",
    role: "landlord",
    kycStatus: "verified",
    state: "Lagos",
    city: "Ikoyi",
    createdAt: "2025-08-12",
    isActive: true,
  },
  {
    id: "u7",
    firstName: "Ibrahim",
    lastName: "Musa",
    email: "ibrahim@gmail.com",
    phone: "07023456789",
    role: "agent",
    kycStatus: "not_started",
    state: "Kano",
    city: "Nassarawa GRA",
    createdAt: "2026-02-18",
    isActive: true,
  },
];

// ── Properties ─────────────────────────────────────────
export const mockProperties: Property[] = [
  {
    id: "p1",
    title: "Luxury 3 Bedroom Flat in Lekki Phase 1",
    description:
      "Beautifully furnished 3 bedroom apartment with modern finishings, 24/7 power supply, and excellent security in the heart of Lekki Phase 1.",
    type: "Flat",
    status: "Available",
    rentType: "Monthly",
    price: 290_000,
    cautionFee: 290_000,
    serviceFee: 350_000,
    bedrooms: 3,
    bathrooms: 3,
    toilets: 4,
    sqft: 1800,
    powerSupplyHours: 22,
    amenities: ["24/7 Power Supply", "Running Water", "Security", "Parking Space", "Swimming Pool", "Gym"],
    images: [],
    state: "Lagos",
    city: "Lekki",
    area: "Phase 1",
    address: "12 Admiralty Way, Lekki Phase 1",
    isVerified: true,
    isFeatured: true,
    landlordId: "u2",
    agentId: "u3",
    views: 342,
    inquiries: 28,
    createdAt: "2026-01-15",
    updatedAt: "2026-03-10",
  },
  {
    id: "p2",
    title: "4 Bedroom Duplex in Maitama",
    description:
      "Spacious 4 bedroom detached duplex with BQ in the serene Maitama district. Close to embassies and top restaurants.",
    type: "Duplex",
    status: "Available",
    rentType: "Monthly",
    price: 670_000,
    cautionFee: 670_000,
    serviceFee: 800_000,
    bedrooms: 4,
    bathrooms: 4,
    toilets: 5,
    sqft: 3200,
    powerSupplyHours: 24,
    amenities: ["24/7 Power Supply", "Security", "Parking Space", "Boys Quarters (BQ)", "Generator", "Gate House"],
    images: [],
    state: "FCT Abuja",
    city: "Maitama",
    area: "Maitama District",
    address: "Plot 45, Yedseram Street, Maitama",
    isVerified: true,
    isFeatured: true,
    landlordId: "u2",
    views: 189,
    inquiries: 15,
    createdAt: "2026-02-01",
    updatedAt: "2026-03-05",
  },
  {
    id: "p3",
    title: "Self-Contain in Yaba",
    description:
      "Cozy self-contained apartment in Yaba, perfect for students and young professionals. Close to UNILAG and major transport links.",
    type: "Self-Contain",
    status: "Available",
    rentType: "Monthly",
    price: 38_000,
    cautionFee: 38_000,
    serviceFee: 45_000,
    bedrooms: 1,
    bathrooms: 1,
    toilets: 1,
    powerSupplyHours: 14,
    amenities: ["Prepaid Meter", "Tiled Floor", "POP Ceiling"],
    images: [],
    state: "Lagos",
    city: "Yaba",
    area: "Abule Oja",
    address: "15 Sabo Road, Yaba",
    isVerified: true,
    isFeatured: false,
    landlordId: "u6",
    agentId: "u3",
    views: 567,
    inquiries: 45,
    createdAt: "2026-01-20",
    updatedAt: "2026-03-01",
  },
  {
    id: "p4",
    title: "2 Bedroom Flat in GRA Port Harcourt",
    description:
      "Well-maintained 2 bedroom flat in the GRA area. Secure estate with constant power supply.",
    type: "Flat",
    status: "Available",
    rentType: "Monthly",
    price: 100_000,
    cautionFee: 100_000,
    serviceFee: 120_000,
    bedrooms: 2,
    bathrooms: 2,
    toilets: 3,
    powerSupplyHours: 20,
    amenities: ["24/7 Power Supply", "Security", "Parking Space", "Generator", "Running Water"],
    images: [],
    state: "Rivers",
    city: "GRA Phase 2",
    area: "GRA",
    address: "22 Peter Odili Road, GRA Phase 2",
    isVerified: true,
    isFeatured: false,
    landlordId: "u6",
    views: 124,
    inquiries: 8,
    createdAt: "2026-02-10",
    updatedAt: "2026-03-08",
  },
  {
    id: "p5",
    title: "Penthouse in Victoria Island",
    description:
      "Premium 3 bedroom penthouse on Victoria Island with panoramic ocean views. Fully serviced building with concierge.",
    type: "Penthouse",
    status: "Available",
    rentType: "Monthly",
    price: 1_250_000,
    cautionFee: 1_250_000,
    serviceFee: 1_500_000,
    bedrooms: 3,
    bathrooms: 3,
    toilets: 4,
    sqft: 2800,
    powerSupplyHours: 24,
    amenities: ["24/7 Power Supply", "Swimming Pool", "Gym", "Security", "Parking Space", "CCTV", "Serviced"],
    images: [],
    state: "Lagos",
    city: "Victoria Island",
    area: "Eko Atlantic",
    address: "Azuri Tower, Eko Atlantic City",
    isVerified: true,
    isFeatured: true,
    landlordId: "u2",
    agentId: "u3",
    views: 89,
    inquiries: 5,
    createdAt: "2026-03-01",
    updatedAt: "2026-03-15",
  },
  {
    id: "p6",
    title: "Event Hall in Ikeja",
    description:
      "Spacious event hall suitable for weddings, conferences, and social gatherings. Capacity for 500 guests.",
    type: "Event Hall",
    status: "Available",
    rentType: "Per Event",
    price: 500_000,
    cautionFee: 200_000,
    serviceFee: 50_000,
    bedrooms: 0,
    bathrooms: 4,
    toilets: 6,
    sqft: 5000,
    powerSupplyHours: 24,
    amenities: ["24/7 Power Supply", "Generator", "Parking Space", "Security"],
    images: [],
    state: "Lagos",
    city: "Ikeja",
    area: "GRA Ikeja",
    address: "5 Allen Avenue, Ikeja GRA",
    isVerified: true,
    isFeatured: false,
    landlordId: "u6",
    views: 230,
    inquiries: 18,
    createdAt: "2026-01-10",
    updatedAt: "2026-02-28",
  },
  {
    id: "p7",
    title: "Mini Flat in Surulere",
    description:
      "Clean and affordable mini flat in the busy Surulere area. Close to National Stadium and shopping centers.",
    type: "Mini Flat",
    status: "Taken",
    rentType: "Monthly",
    price: 50_000,
    cautionFee: 50_000,
    serviceFee: 60_000,
    bedrooms: 1,
    bathrooms: 1,
    toilets: 1,
    powerSupplyHours: 12,
    amenities: ["Prepaid Meter", "Tiled Floor", "Wardrobes"],
    images: [],
    state: "Lagos",
    city: "Surulere",
    area: "Ojuelegba",
    address: "8 Bode Thomas Street, Surulere",
    isVerified: true,
    isFeatured: false,
    landlordId: "u6",
    views: 410,
    inquiries: 32,
    createdAt: "2025-12-05",
    updatedAt: "2026-01-20",
  },
  {
    id: "p8",
    title: "3 Bedroom Terrace in Gwarinpa",
    description:
      "Modern 3 bedroom terrace duplex in a well-planned estate in Gwarinpa. Family-friendly neighbourhood.",
    type: "Terrace",
    status: "Available",
    rentType: "Monthly",
    price: 335_000,
    cautionFee: 335_000,
    serviceFee: 400_000,
    bedrooms: 3,
    bathrooms: 3,
    toilets: 4,
    powerSupplyHours: 18,
    amenities: ["Security", "Parking Space", "Children Playground", "Newly Built"],
    images: [],
    state: "FCT Abuja",
    city: "Gwarinpa",
    area: "3rd Avenue",
    address: "Block C4, 3rd Avenue, Gwarinpa",
    isVerified: false,
    isFeatured: false,
    landlordId: "u2",
    views: 67,
    inquiries: 4,
    createdAt: "2026-03-10",
    updatedAt: "2026-03-15",
  },
];

// ── Applications ───────────────────────────────────────
export const mockApplications: PropertyApplication[] = [
  {
    id: "app1",
    propertyId: "p1",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    tenantEmail: "chinedu@gmail.com",
    status: "approved",
    submittedAt: "2026-02-20",
    reviewedAt: "2026-02-25",
  },
  {
    id: "app2",
    propertyId: "p3",
    tenantId: "u5",
    tenantName: "Oluwaseun Adeyemi",
    tenantEmail: "seun@gmail.com",
    status: "under_review",
    submittedAt: "2026-03-10",
  },
  {
    id: "app3",
    propertyId: "p2",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    tenantEmail: "chinedu@gmail.com",
    status: "submitted",
    submittedAt: "2026-03-18",
  },
  {
    id: "app4",
    propertyId: "p5",
    tenantId: "u5",
    tenantName: "Oluwaseun Adeyemi",
    tenantEmail: "seun@gmail.com",
    status: "rejected",
    submittedAt: "2026-02-15",
    reviewedAt: "2026-02-20",
    notes: "KYC verification incomplete",
  },
];

// ── Leases ─────────────────────────────────────────────
export const mockLeases: Lease[] = [
  {
    id: "l1",
    propertyId: "p1",
    propertyTitle: "Luxury 3 Bedroom Flat in Lekki Phase 1",
    propertyAddress: "12 Admiralty Way, Lekki Phase 1, Lagos",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    landlordId: "u2",
    landlordName: "Aisha Abdullahi",
    status: "active",
    startDate: "2026-03-01",
    endDate: "2027-02-28",
    rentAmount: 290_000,
    cautionFee: 290_000,
    serviceFee: 350_000,
    isSigned: true,
    signedAt: "2026-02-28",
    createdAt: "2026-02-25",
  },
  {
    id: "l2",
    propertyId: "p7",
    propertyTitle: "Mini Flat in Surulere",
    propertyAddress: "8 Bode Thomas Street, Surulere, Lagos",
    tenantId: "u5",
    tenantName: "Oluwaseun Adeyemi",
    landlordId: "u6",
    landlordName: "Amaka Eze",
    status: "renewal_due",
    startDate: "2025-04-01",
    endDate: "2026-03-31",
    rentAmount: 50_000,
    cautionFee: 50_000,
    serviceFee: 60_000,
    isSigned: true,
    signedAt: "2025-03-28",
    createdAt: "2025-03-25",
  },
];

// ── Payments ───────────────────────────────────────────
export const mockPayments: Payment[] = [
  {
    id: "pay1",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    tenantEmail: "chinedu@gmail.com",
    landlordId: "u2",
    propertyId: "p1",
    propertyTitle: "3 Bed Flat, Lekki Phase 1",
    amount: 290_000,
    type: "rent",
    status: "paid",
    reference: "SR-PAY-2026-001",
    dueDate: "2026-03-01",
    paidAt: "2026-02-28",
    createdAt: "2026-02-15",
  },
  {
    id: "pay2",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    tenantEmail: "chinedu@gmail.com",
    propertyId: "p1",
    propertyTitle: "3 Bed Flat, Lekki Phase 1",
    amount: 290_000,
    type: "caution_fee",
    status: "paid",
    reference: "SR-PAY-2026-002",
    dueDate: "2026-03-01",
    paidAt: "2026-02-28",
    createdAt: "2026-02-15",
  },
  {
    id: "pay3",
    tenantId: "u5",
    tenantName: "Oluwaseun Adeyemi",
    tenantEmail: "seun@gmail.com",
    landlordId: "u6",
    propertyId: "p7",
    propertyTitle: "Mini Flat, Surulere",
    amount: 50_000,
    type: "rent",
    status: "pending",
    reference: "SR-PAY-2026-003",
    dueDate: "2026-04-01",
    createdAt: "2026-03-15",
  },
  {
    id: "pay4",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    tenantEmail: "chinedu@gmail.com",
    propertyId: "p1",
    propertyTitle: "3 Bed Flat, Lekki Phase 1",
    amount: 350_000,
    type: "service_fee",
    status: "paid",
    reference: "SR-PAY-2026-004",
    dueDate: "2026-03-01",
    paidAt: "2026-02-28",
    createdAt: "2026-02-15",
  },
  {
    id: "pay5",
    tenantName: "Emeka Nwosu",
    tenantEmail: "emeka@gmail.com",
    propertyId: "p1",
    propertyTitle: "Referral · Tobi Adekunle signed lease",
    amount: 5_000,
    type: "referral_reward",
    status: "paid",
    reference: "SR-PAY-2026-005",
    dueDate: "2026-03-05",
    paidAt: "2026-03-05",
    createdAt: "2026-03-01",
  },
  {
    id: "pay6",
    tenantName: "Emeka Nwosu",
    tenantEmail: "emeka@gmail.com",
    propertyId: "p3",
    propertyTitle: "Referral · Ngozi Uche listed property",
    amount: 5_000,
    type: "referral_reward",
    status: "pending",
    reference: "SR-PAY-2026-006",
    dueDate: "2026-04-01",
    createdAt: "2026-03-15",
  },
];

// ── Maintenance Requests ───────────────────────────────
export const mockMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: "m1",
    propertyId: "p1",
    propertyTitle: "3 Bed Flat, Lekki Phase 1",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    category: "plumbing",
    title: "Kitchen sink leaking",
    description: "The kitchen sink has been leaking for two days. Water is pooling under the cabinet.",
    priority: "high",
    status: "in_progress",
    images: [],
    createdAt: "2026-03-15",
    updatedAt: "2026-03-16",
  },
  {
    id: "m2",
    propertyId: "p7",
    propertyTitle: "Mini Flat, Surulere",
    tenantId: "u5",
    tenantName: "Oluwaseun Adeyemi",
    category: "electrical",
    title: "Power outlet not working",
    description: "The power outlet in the bedroom stopped working after the last power surge.",
    priority: "medium",
    status: "open",
    images: [],
    createdAt: "2026-03-18",
    updatedAt: "2026-03-18",
  },
  {
    id: "m3",
    propertyId: "p1",
    propertyTitle: "3 Bed Flat, Lekki Phase 1",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    category: "generator",
    title: "Generator servicing needed",
    description: "The standby generator needs routine servicing. It has been making unusual noise.",
    priority: "low",
    status: "resolved",
    images: [],
    createdAt: "2026-02-20",
    updatedAt: "2026-02-25",
    resolvedAt: "2026-02-25",
  },
];

// ── Notifications ──────────────────────────────────────
export const mockNotifications: Notification[] = [
  { id: "n1", title: "Rent Payment Due", message: "Your rent for Lekki Phase 1 is due in 7 days.", type: "warning", read: false, createdAt: "2026-03-22", link: "/customer/payments" },
  { id: "n2", title: "Application Approved", message: "Your application for 3 Bedroom Flat in Lekki has been approved!", type: "success", read: false, createdAt: "2026-02-25", link: "/customer/applications" },
  { id: "n3", title: "Maintenance Update", message: "Your kitchen sink repair is now in progress.", type: "info", read: true, createdAt: "2026-03-16", link: "/customer/maintenance" },
  { id: "n4", title: "New Tenant Application", message: "Oluwaseun Adeyemi applied for Self-Contain in Yaba.", type: "info", read: false, createdAt: "2026-03-10", link: "/landlord/applications" },
  { id: "n5", title: "Commission Earned", message: "You earned ₦350,000 commission on Lekki Phase 1 deal.", type: "success", read: true, createdAt: "2026-03-05", link: "/agent/commissions" },
];

// ── Activity Feed ──────────────────────────────────────
export const mockActivity: ActivityItem[] = [
  { id: "a1", type: "payment", title: "Rent payment received", description: "Chinedu Okafor paid ₦3,500,000 for Lekki Phase 1", timestamp: "2026-03-20T10:30:00" },
  { id: "a2", type: "application", title: "New application", description: "Oluwaseun Adeyemi applied for Self-Contain in Yaba", timestamp: "2026-03-18T14:20:00" },
  { id: "a3", type: "maintenance", title: "Maintenance request", description: "Kitchen sink repair request from Chinedu Okafor", timestamp: "2026-03-15T09:00:00" },
  { id: "a4", type: "lease", title: "Lease signed", description: "Lease signed for 3 Bedroom Flat in Lekki Phase 1", timestamp: "2026-02-28T16:45:00" },
  { id: "a5", type: "listing", title: "New listing", description: "Penthouse in Victoria Island listed by Aisha Abdullahi", timestamp: "2026-03-01T11:00:00" },
  { id: "a6", type: "review", title: "New review", description: "Chinedu rated Lekki Phase 1 property 4.5 stars", timestamp: "2026-03-12T08:15:00" },
];

// ── Property Reviews (tenants reviewing properties) ────
export const mockPropertyReviews: PropertyReview[] = [
  {
    id: "pr1",
    propertyId: "p1",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    rating: 4.5,
    title: "Genuinely a peaceful home",
    comment:
      "Lived here for 9 months. Power supply is honest — they advertised 22 hours and that's roughly what we get. Security is tight, the swimming pool is well kept. Only gripe: parking gets crowded on weekends.",
    stayLength: "9 months",
    createdAt: "2026-03-12",
  },
  {
    id: "pr2",
    propertyId: "p1",
    tenantId: "u5",
    tenantName: "Oluwaseun Adeyemi",
    rating: 4,
    title: "Worth the price tag",
    comment:
      "Beautiful finishings and the gym is a nice touch. Internet in the area is solid. Service charge response time could be quicker.",
    stayLength: "6 months",
    createdAt: "2026-02-04",
  },
  {
    id: "pr3",
    propertyId: "p3",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    rating: 3.5,
    title: "Decent for the price",
    comment:
      "Self-contain in Yaba, what you'd expect. Power is there about 14 hours daily as listed, no surprises. Landlord is responsive.",
    stayLength: "1 year",
    createdAt: "2026-01-22",
  },
  {
    id: "pr4",
    propertyId: "p2",
    tenantId: "u5",
    tenantName: "Oluwaseun Adeyemi",
    rating: 5,
    title: "Maitama at its finest",
    comment:
      "Power runs 24/7 between mains and inverter. Quiet street, easy access to embassies. Highly recommend if it's within budget.",
    stayLength: "2 years",
    createdAt: "2026-02-28",
  },
  {
    id: "pr5",
    propertyId: "p4",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    rating: 4,
    title: "Solid GRA flat",
    comment:
      "Generator kicks in promptly when NEPA goes off. Estate is secure. Water pressure can drop in the dry season.",
    stayLength: "8 months",
    createdAt: "2026-03-01",
  },
];

// ── Tenant Reviews (landlords/agents reviewing tenants) ─
export const mockTenantReviews: TenantReview[] = [
  {
    id: "tr1",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    reviewerId: "u2",
    reviewerName: "Aisha Abdullahi",
    reviewerRole: "landlord",
    propertyId: "p1",
    propertyTitle: "Luxury 3 Bedroom Flat in Lekki Phase 1",
    rating: 5,
    comment:
      "One of the easiest tenants I've had. Pays rent before the due date, takes care of the apartment, and communicates clearly. Would lease to him again.",
    paymentTimeliness: "excellent",
    propertyCare: "excellent",
    createdAt: "2026-03-05",
  },
  {
    id: "tr2",
    tenantId: "u1",
    tenantName: "Chinedu Okafor",
    reviewerId: "u3",
    reviewerName: "Emeka Nwosu",
    reviewerRole: "agent",
    propertyId: "p1",
    propertyTitle: "Luxury 3 Bedroom Flat in Lekki Phase 1",
    rating: 4.5,
    comment:
      "Smooth onboarding. Showed up to inspection on time, asked the right questions, and the deal closed within a week.",
    paymentTimeliness: "excellent",
    propertyCare: "good",
    createdAt: "2026-02-26",
  },
  {
    id: "tr3",
    tenantId: "u5",
    tenantName: "Oluwaseun Adeyemi",
    reviewerId: "u6",
    reviewerName: "Amaka Eze",
    reviewerRole: "landlord",
    propertyId: "p7",
    propertyTitle: "Mini Flat in Surulere",
    rating: 3.5,
    comment:
      "Generally fine — keeps the place neat. Rent has been late twice in the last twelve months but always settled within the grace window.",
    paymentTimeliness: "fair",
    propertyCare: "good",
    createdAt: "2026-03-10",
  },
];

// ── Agent Deals ────────────────────────────────────────
export const mockDeals: DealStage[] = [
  { id: "d1", propertyId: "p1", propertyTitle: "3 Bed Flat, Lekki Phase 1", clientName: "Chinedu Okafor", clientPhone: "08012345678", stage: "closed", value: 350_000, createdAt: "2026-02-10", updatedAt: "2026-03-01" },
  { id: "d2", propertyId: "p3", propertyTitle: "Self-Contain, Yaba", clientName: "Oluwaseun Adeyemi", clientPhone: "09087654321", stage: "viewing", value: 45_000, createdAt: "2026-03-12", updatedAt: "2026-03-18" },
  { id: "d3", propertyId: "p5", propertyTitle: "Penthouse, Victoria Island", clientName: "Bola Tinubu Jr", clientPhone: "08055667788", stage: "negotiation", value: 1_500_000, createdAt: "2026-03-05", updatedAt: "2026-03-20" },
  { id: "d4", propertyId: "p4", propertyTitle: "2 Bed Flat, GRA PH", clientName: "Ada Okonkwo", clientPhone: "07099887766", stage: "prospect", value: 120_000, createdAt: "2026-03-19", updatedAt: "2026-03-19" },
];

// ── Revenue Chart Data ─────────────────────────────────
export const mockRevenueData = [
  { month: "Oct", income: 2_800_000, expense: 1_200_000 },
  { month: "Nov", income: 3_200_000, expense: 1_400_000 },
  { month: "Dec", income: 4_100_000, expense: 1_800_000 },
  { month: "Jan", income: 3_800_000, expense: 1_600_000 },
  { month: "Feb", income: 5_200_000, expense: 2_100_000 },
  { month: "Mar", income: 4_600_000, expense: 1_900_000 },
];
