import type {
  ServiceCatalogItem,
  ServiceRequest,
  ServiceFrequency,
  DayOfWeek,
} from "@/types/service";

export const DEFAULT_SERVICE_CATALOG: ServiceCatalogItem[] = [
  {
    id: "svc-cleaning",
    name: "House cleaning",
    category: "cleaning",
    tagline: "Vetted cleaners, eco-friendly products.",
    description:
      "Deep or routine cleaning across living rooms, bedrooms, kitchens and bathrooms. Includes mopping, dusting, bin removal and surface sanitisation.",
    basePrice: 12000,
    unit: "per visit",
    durationMinutes: 180,
    supportedFrequencies: ["one_off", "weekly", "biweekly", "monthly"],
    features: ["Eco-friendly products", "Vetted cleaners", "Insurance covered"],
    popular: true,
  },
  {
    id: "svc-laundry",
    name: "Laundry & ironing",
    category: "laundry",
    tagline: "Pickup, wash, fold, deliver.",
    description:
      "Doorstep pickup of laundry by 9 AM. Washed, dried, ironed and returned the next morning. Eco-detergent. Per-kg pricing or fixed bag.",
    basePrice: 6500,
    unit: "per visit",
    durationMinutes: 60,
    supportedFrequencies: ["one_off", "weekly", "biweekly"],
    features: ["Same-day option", "Eco detergent", "Hand-finished ironing"],
    popular: true,
  },
  {
    id: "svc-fumigation",
    name: "Fumigation & pest control",
    category: "fumigation",
    tagline: "Bedbugs, roaches, mosquitoes — gone.",
    description:
      "NAFDAC-approved chemicals applied by a licensed technician. Safe re-entry within 90 minutes. 30-day satisfaction guarantee.",
    basePrice: 25000,
    unit: "per visit",
    durationMinutes: 90,
    supportedFrequencies: ["one_off", "monthly"],
    features: ["NAFDAC-approved", "Pet-safe option", "30-day guarantee"],
  },
  {
    id: "svc-gardening",
    name: "Gardening & lawn",
    category: "gardening",
    tagline: "Trimmed lawns, healthy plants.",
    description:
      "Lawn mowing, edging, hedge trimming, plant care, and waste disposal. Includes a monthly soil & watering report.",
    basePrice: 18000,
    unit: "per visit",
    durationMinutes: 120,
    supportedFrequencies: ["weekly", "biweekly", "monthly"],
    features: ["Bring our own equipment", "Garden waste removal"],
  },
  {
    id: "svc-plumbing",
    name: "Plumbing on call",
    category: "plumbing",
    tagline: "Same-day fixes, transparent pricing.",
    description:
      "Leaks, clogged drains, low pressure, water heater issues — diagnosed and fixed by a licensed plumber. Parts billed transparently.",
    basePrice: 15000,
    unit: "per visit",
    durationMinutes: 90,
    supportedFrequencies: ["one_off"],
    features: ["Licensed pros", "Transparent parts cost", "Same-day"],
  },
  {
    id: "svc-electrician",
    name: "Electrician on call",
    category: "electrician",
    tagline: "Wiring, fittings, surge protection.",
    description:
      "From flickering bulbs to full circuit reviews. Licensed electricians who know Lagos and Abuja building codes.",
    basePrice: 16000,
    unit: "per visit",
    durationMinutes: 90,
    supportedFrequencies: ["one_off"],
    features: ["NEMSA-certified", "Surge audits", "Same-day"],
  },
  {
    id: "svc-ac",
    name: "AC servicing",
    category: "ac_servicing",
    tagline: "Cool air, lower bills.",
    description:
      "Coil cleaning, gas top-up, filter replacement and leak detection. Up to 4 split units per visit.",
    basePrice: 22000,
    unit: "per visit",
    durationMinutes: 120,
    supportedFrequencies: ["one_off", "monthly"],
    features: ["Up to 4 units", "Gas refill included"],
  },
  {
    id: "svc-chef",
    name: "Private chef",
    category: "chef",
    tagline: "Home-cooked, plated to order.",
    description:
      "A vetted chef preps, cooks, and plates a 3-course menu of your choice. Groceries handled if requested.",
    basePrice: 35000,
    unit: "per visit",
    durationMinutes: 240,
    supportedFrequencies: ["one_off", "weekly", "biweekly"],
    features: ["Custom menu", "Groceries optional", "Diet-aware"],
  },
  {
    id: "svc-security",
    name: "Night security",
    category: "security",
    tagline: "Trained guards, on rotation.",
    description:
      "A vetted, trained guard on rotation 8 PM – 6 AM. Includes incident logging and emergency dispatch hotline.",
    basePrice: 14000,
    unit: "per visit",
    durationMinutes: 600,
    supportedFrequencies: ["daily", "weekly"],
    features: ["Background-checked", "Incident logbook", "Emergency dispatch"],
  },
  {
    id: "svc-errand",
    name: "Personal errands",
    category: "errand",
    tagline: "Groceries, packages, queue-jumping.",
    description:
      "A trusted runner handles groceries, package pickups, embassy queues, parcel drop-offs, and more. Hourly billing.",
    basePrice: 8000,
    unit: "per hour",
    durationMinutes: 60,
    supportedFrequencies: ["one_off", "weekly", "biweekly"],
    features: ["Hourly billing", "Live location share"],
  },
  {
    id: "svc-contents-insurance",
    name: "Household contents insurance",
    category: "insurance",
    tagline: "Cover your TVs, fridge, sofas — up to ₦5M.",
    description:
      "Underwritten by Leadway. Covers theft, fire, flood and accidental damage to household electronics, furniture and personal items. Same-day claims via the SmoothRent app.",
    basePrice: 3500,
    unit: "per month",
    durationMinutes: 0,
    supportedFrequencies: ["monthly"],
    features: ["Up to ₦5M cover", "Same-day claims", "Underwritten by Leadway"],
    popular: true,
  },
  {
    id: "svc-tenant-liability",
    name: "Tenant liability insurance",
    category: "insurance",
    tagline: "Sleep easy on the caution fee.",
    description:
      "Protects you against accidental damage to the landlord's property — from a burst pipe to a fire. Up to ₦2M cover, replaces the back-and-forth on your refundable caution fee.",
    basePrice: 2200,
    unit: "per month",
    durationMinutes: 0,
    supportedFrequencies: ["monthly"],
    features: ["Up to ₦2M cover", "Caution-fee top-up", "Cancel anytime"],
  },
  {
    id: "svc-surge-cover",
    name: "Appliance surge protection",
    category: "insurance",
    tagline: "Replace fried fridges, ACs, TVs.",
    description:
      "Covers electrical appliances damaged by power surges or voltage spikes. Pays out within 7 days. Includes one free electrician visit per claim.",
    basePrice: 1500,
    unit: "per month",
    durationMinutes: 0,
    supportedFrequencies: ["monthly"],
    features: ["Up to ₦1.5M cover", "7-day payout", "Free electrician visit"],
  },
];

export const FREQUENCY_LABEL: Record<ServiceFrequency, string> = {
  one_off: "One-off",
  daily: "Daily",
  weekly: "Weekly",
  biweekly: "Every 2 weeks",
  monthly: "Monthly",
};

export const DAY_LABEL: Record<DayOfWeek, { short: string; long: string }> = {
  0: { short: "Sun", long: "Sunday" },
  1: { short: "Mon", long: "Monday" },
  2: { short: "Tue", long: "Tuesday" },
  3: { short: "Wed", long: "Wednesday" },
  4: { short: "Thu", long: "Thursday" },
  5: { short: "Fri", long: "Friday" },
  6: { short: "Sat", long: "Saturday" },
};

export const DAYS_OF_WEEK: DayOfWeek[] = [0, 1, 2, 3, 4, 5, 6];

// ── Backwards-compat alias for callers that still import SERVICE_CATALOG.
// Prefer `useServiceCatalog()` from "@/lib/service-catalog-store" for live admin edits.
export const SERVICE_CATALOG = DEFAULT_SERVICE_CATALOG;

export const mockServiceRequests: ServiceRequest[] = [
  {
    id: "sr-1",
    tenantId: "u1",
    leaseId: "l1",
    propertyId: "p1",
    propertyTitle: "Luxury 3 Bedroom Flat in Lekki Phase 1",
    serviceId: "svc-cleaning",
    serviceName: "House cleaning",
    category: "cleaning",
    frequency: "weekly",
    daysOfWeek: [6],
    preferredTime: "09:00",
    status: "scheduled",
    pricePerVisit: 12000,
    startDate: "2026-03-07",
    nextVisit: "2026-04-04",
    lastVisit: "2026-03-28",
    visitsCompleted: 4,
    vendorName: "ShineRight Cleaners",
    createdAt: "2026-03-01",
  },
  {
    id: "sr-2",
    tenantId: "u1",
    leaseId: "l1",
    propertyId: "p1",
    propertyTitle: "Luxury 3 Bedroom Flat in Lekki Phase 1",
    serviceId: "svc-laundry",
    serviceName: "Laundry & ironing",
    category: "laundry",
    frequency: "weekly",
    daysOfWeek: [1, 4],
    preferredTime: "08:00",
    status: "scheduled",
    pricePerVisit: 6500,
    startDate: "2026-03-10",
    nextVisit: "2026-04-29",
    lastVisit: "2026-04-25",
    visitsCompleted: 14,
    vendorName: "FreshFold Laundry",
    createdAt: "2026-03-04",
    notes: "Use eco-detergent only. No fabric softener on the bedsheets.",
  },
  {
    id: "sr-3",
    tenantId: "u1",
    leaseId: "l1",
    propertyId: "p1",
    propertyTitle: "Luxury 3 Bedroom Flat in Lekki Phase 1",
    serviceId: "svc-fumigation",
    serviceName: "Fumigation & pest control",
    category: "fumigation",
    frequency: "monthly",
    daysOfWeek: [6],
    preferredTime: "10:00",
    status: "completed",
    pricePerVisit: 25000,
    startDate: "2026-03-14",
    lastVisit: "2026-04-12",
    visitsCompleted: 2,
    vendorName: "PestNet Lagos",
    createdAt: "2026-03-12",
  },
];
